# Memoria para Gradle JVM y Dexing de Compose
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m -XX:+HeapDumpOnOutOfMemoryError

# Memoria y estabilidad para el demonio de Kotlin
kotlin.daemon.jvmargs=-Xmx2048m
kotlin.incremental=false

# Optimizaciones
org.gradle.parallel=true
org.gradle.caching=false

# AndroidX y R8
android.useAndroidX=true
android.nonTransitiveRClass=true

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
